{
 "title": "Network Traffic",
 "tags": [
  "network",
  "node-exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Bandwidth Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Rx Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=\"$node\", job=\"$job\", device!~\"lo|veth.*|docker.*|br-.*\"}[$__rate_interval]))",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Current Tx Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=\"$node\", job=\"$job\", device!~\"lo|veth.*|docker.*|br-.*\"}[$__rate_interval]))",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "24h Received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=\"$node\", job=\"$job\", device!~\"lo|veth.*|docker.*|br-.*\"}[24h]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "24h Transmitted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=\"$node\", job=\"$job\", device!~\"lo|veth.*|docker.*|br-.*\"}[24h]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Conntrack Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=\"$node\", job=\"$job\"} / node_nf_conntrack_entries_limit{instance=\"$node\", job=\"$job\"} * 100",
     "legendFormat": "Utilization"
    }
   ]
  },
  { "title": "Per-Interface Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Receive Bandwidth by Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\", job=\"$job\", device!~\"lo|veth.*|docker.*|br-.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} rx"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth by Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\", job=\"$job\", device!~\"lo|veth.*|docker.*|br-.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} tx"
    }
   ]
  },
  { "title": "Packets & Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Packets per Second by Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=\"$node\", job=\"$job\", device!~\"lo|veth.*|docker.*|br-.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} rx"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=\"$node\", job=\"$job\", device!~\"lo|veth.*|docker.*|br-.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} tx"
    }
   ]
  },
  {
   "title": "Errors & Drops Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{instance=\"$node\", job=\"$job\", device!~\"lo|veth.*|docker.*|br-.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} rx errors"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"$node\", job=\"$job\", device!~\"lo|veth.*|docker.*|br-.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} tx errors"
    },
    {
     "expr": "irate(node_network_receive_drop_total{instance=\"$node\", job=\"$job\", device!~\"lo|veth.*|docker.*|br-.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} rx drops"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{instance=\"$node\", job=\"$job\", device!~\"lo|veth.*|docker.*|br-.*\"}[$__rate_interval])",
     "legendFormat": "{{device}} tx drops"
    }
   ]
  },
  { "title": "TCP Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "TCP Segments & Retransmits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "segment/s" } },
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "in segments"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "out segments"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "retransmits"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "inuse"
    },
    {
     "expr": "node_sockstat_TCP_orphan{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "orphan"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "time-wait"
    }
   ]
  },
  { "title": "Connection Tracking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Conntrack Entries vs Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Socket Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_sockstat_UDP_inuse{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "UDP inuse"
    },
    {
     "expr": "node_sockstat_RAW_inuse{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "RAW inuse"
    },
    {
     "expr": "node_sockstat_FRAG_inuse{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "FRAG inuse"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "TCP inuse"
    }
   ]
  }
 ]
}